#!/usr/bin/env python3
"""檔案用途：提供 workflow-core projection/bootstrap 的最小可執行骨架。"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from workflow_core_manifest import (  # noqa: E402
    get_managed_patterns,
    get_projection_artifact_path,
    get_required_live_paths,
    load_manifest,
    manifest_default_path,
    normalize_path,
    path_matches_pattern,
    pattern_anchor,
)
from workflow_core_obsidian_restricted_mount import run_generate_downstream_obsidian_mount  # noqa: E402


EXIT_PASS = 0
EXIT_WARN = 10
EXIT_FAIL = 20
EXIT_ERROR = 30
INDEX_PATH = "doc/implementation_plan_index.md"
INDEX_PLACEHOLDER = "# Implementation Plan Index\n\n> Placeholder generated by workflow_core_projection.py bootstrap stub.\n"


def classify_required_live_paths(repo_root: Path, manifest: dict) -> dict[str, list[str]]:
    existing: list[str] = []
    missing: list[str] = []
    for pattern in get_required_live_paths(manifest):
        anchor = pattern_anchor(pattern)
        if not anchor:
            missing.append(pattern)
            continue
        target = repo_root / anchor
        if target.exists():
            existing.append(pattern)
        else:
            missing.append(pattern)
    return {"existing": existing, "missing": missing}


def bootstrap_overlay_index(repo_root: Path) -> str | None:
    index_path = repo_root / INDEX_PATH
    if index_path.exists():
        return None
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(INDEX_PLACEHOLDER, encoding="utf-8")
    return normalize_path(str(index_path.relative_to(repo_root)))


def ensure_required_live_path_anchors(repo_root: Path, manifest: dict) -> list[str]:
    created_paths: list[str] = []
    for pattern in get_required_live_paths(manifest):
        anchor = pattern_anchor(pattern)
        if not anchor:
            continue
        target = repo_root / anchor
        if target.exists():
            continue
        if any(char in pattern for char in "*?[") or pattern.endswith("/**"):
            target.mkdir(parents=True, exist_ok=True)
            created_paths.append(normalize_path(str(target.relative_to(repo_root))))
    return created_paths


def select_managed_paths(source_root: Path, manifest: dict) -> list[str]:
    managed_patterns = get_managed_patterns(manifest)
    selected_paths: list[str] = []
    for path in source_root.rglob("*"):
        if not path.is_file():
            continue
        rel_path = normalize_path(str(path.relative_to(source_root)))
        if any(path_matches_pattern(rel_path, pattern) for pattern in managed_patterns):
            selected_paths.append(rel_path)
    return sorted(set(selected_paths))


def materialize_managed_paths(repo_root: Path, source_root: Path, selected_paths: list[str]) -> list[str]:
    projected_paths: list[str] = []
    for rel_path in selected_paths:
        source_path = source_root / rel_path
        target_path = repo_root / rel_path
        if not source_path.exists():
            continue
        if source_path.resolve() == target_path.resolve():
            projected_paths.append(rel_path)
            continue
        target_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, target_path)
        projected_paths.append(rel_path)
    return projected_paths


def run_projection(
    repo_root: Path,
    manifest_path: Path,
    source_root: Path | None = None,
    bootstrap_overlay_index_file: bool = False,
    emit_obsidian_restricted_mount_sample: bool = False,
    obsidian_mount_output_dir: Path | None = None,
    force_obsidian_mount_sample: bool = False,
) -> dict:
    manifest = load_manifest(manifest_path)
    projection_artifact_path = get_projection_artifact_path(manifest)
    effective_source_root = (source_root or repo_root).resolve()
    if not effective_source_root.exists():
        raise FileNotFoundError(f"projection source root does not exist: {effective_source_root}")

    created_paths = ensure_required_live_path_anchors(repo_root, manifest)
    selected_paths = select_managed_paths(effective_source_root, manifest)
    projected_paths = materialize_managed_paths(repo_root, effective_source_root, selected_paths)

    checks = classify_required_live_paths(repo_root, manifest)

    missing_paths = list(checks["missing"])
    notes: list[str] = []

    if bootstrap_overlay_index_file and INDEX_PATH in missing_paths:
        created = bootstrap_overlay_index(repo_root)
        if created:
            created_paths.append(created)
            missing_paths = [item for item in missing_paths if item != INDEX_PATH]
            notes.append("bootstrapped downstream overlay index placeholder")

    mount_result = None
    if emit_obsidian_restricted_mount_sample:
        mount_result = run_generate_downstream_obsidian_mount(
            repo_root=repo_root,
            output_dir=obsidian_mount_output_dir,
            force=force_obsidian_mount_sample,
        )
        notes.extend(mount_result.get("notes", []))

    if missing_paths:
        status = "fail"
        notes.append("projection/bootstrap found missing required live paths after materialization")
    elif created_paths:
        status = "warn"
        notes.append("projection/bootstrap created placeholder downstream overlay artifacts")
    else:
        status = "pass"
        notes.append("projection/bootstrap materialized managed live paths and validated required anchors")

    return {
        "status": status,
        "repo_root": str(repo_root.resolve()),
        "manifest_path": str(manifest_path.resolve()),
        "source_root": str(effective_source_root),
        "projection_artifact_path": projection_artifact_path,
        "existing_required_live_paths": checks["existing"],
        "missing_required_live_paths": missing_paths,
        "created_paths": created_paths,
        "projected_paths": projected_paths,
        "obsidian_mount_sample_generated": bool(mount_result),
        "obsidian_mount_output_dir": str(Path(mount_result["output_dir"]).resolve()) if mount_result else None,
        "notes": notes,
    }


def run_projection_stub(
    repo_root: Path,
    manifest_path: Path,
    bootstrap_overlay_index_file: bool = False,
    source_root: Path | None = None,
    emit_obsidian_restricted_mount_sample: bool = False,
    obsidian_mount_output_dir: Path | None = None,
    force_obsidian_mount_sample: bool = False,
) -> dict:
    return run_projection(
        repo_root=repo_root,
        manifest_path=manifest_path,
        source_root=source_root,
        bootstrap_overlay_index_file=bootstrap_overlay_index_file,
        emit_obsidian_restricted_mount_sample=emit_obsidian_restricted_mount_sample,
        obsidian_mount_output_dir=obsidian_mount_output_dir,
        force_obsidian_mount_sample=force_obsidian_mount_sample,
    )


def format_text_report(result: dict) -> str:
    lines = [
        f"workflow-core projection: {result['status']}",
        f"repo_root: {result['repo_root']}",
        f"manifest_path: {result['manifest_path']}",
        f"source_root: {result['source_root']}",
        f"projection_artifact_path: {result['projection_artifact_path']}",
    ]
    lines.append(f"existing_required_live_paths: {len(result['existing_required_live_paths'])}")
    for item in result["existing_required_live_paths"]:
        lines.append(f"  - {item}")
    lines.append(f"missing_required_live_paths: {len(result['missing_required_live_paths'])}")
    for item in result["missing_required_live_paths"]:
        lines.append(f"  - {item}")
    if result["created_paths"]:
        lines.append("created_paths:")
        for item in result["created_paths"]:
            lines.append(f"  - {item}")
    if result["projected_paths"]:
        lines.append("projected_paths:")
        for item in result["projected_paths"]:
            lines.append(f"  - {item}")
    lines.append(f"obsidian_mount_sample_generated: {result['obsidian_mount_sample_generated']}")
    if result["obsidian_mount_output_dir"]:
        lines.append(f"obsidian_mount_output_dir: {result['obsidian_mount_output_dir']}")
    if result["notes"]:
        lines.append("notes:")
        for item in result["notes"]:
            lines.append(f"  - {item}")
    return "\n".join(lines)


def exit_code_for_status(status: str) -> int:
    if status == "pass":
        return EXIT_PASS
    if status == "warn":
        return EXIT_WARN
    if status == "fail":
        return EXIT_FAIL
    return EXIT_ERROR


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd(), help="Repo 根目錄（預設：目前目錄）")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="workflow-core canonical manifest path（預設：<repo-root>/core_ownership_manifest.yml）",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=None,
        help="可選的 staged/export source root；未指定時直接以 repo-root 當 source",
    )
    parser.add_argument(
        "--bootstrap-overlay-index",
        action="store_true",
        help="若 doc/implementation_plan_index.md 缺失，建立最小 placeholder 作為 bootstrap stub",
    )
    parser.add_argument(
        "--emit-obsidian-restricted-mount-sample",
        dest="emit_obsidian_restricted_mount_sample",
        action="store_true",
        help="額外產出 downstream restricted Obsidian mount sample（opt-in）",
    )
    parser.add_argument(
        "--setup-obsidian-restricted-access",
        dest="emit_obsidian_restricted_mount_sample",
        action="store_true",
        help="高層 alias：初始化 downstream restricted Obsidian access sample",
    )
    parser.add_argument(
        "--obsidian-mount-output-dir",
        type=Path,
        default=None,
        help="restricted mount sample 輸出目錄（預設：<repo-root>/.devcontainer）",
    )
    parser.add_argument(
        "--force-obsidian-mount-sample",
        action="store_true",
        help="若 sample 已存在且內容不同，允許覆蓋",
    )
    parser.add_argument("--json", action="store_true", help="輸出 JSON")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    manifest_path = args.manifest.resolve() if args.manifest else manifest_default_path(repo_root)
    try:
        result = run_projection_stub(
            repo_root=repo_root,
            manifest_path=manifest_path,
            source_root=args.source_root.resolve() if args.source_root else None,
            bootstrap_overlay_index_file=bool(args.bootstrap_overlay_index),
            emit_obsidian_restricted_mount_sample=bool(args.emit_obsidian_restricted_mount_sample),
            obsidian_mount_output_dir=args.obsidian_mount_output_dir.resolve() if args.obsidian_mount_output_dir else None,
            force_obsidian_mount_sample=bool(args.force_obsidian_mount_sample),
        )
    except Exception as exc:
        if args.json:
            print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False, indent=2), file=sys.stderr)
        else:
            print(f"workflow-core projection stub error: {exc}", file=sys.stderr)
        return EXIT_ERROR

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(format_text_report(result))
    return exit_code_for_status(result["status"])


if __name__ == "__main__":
    raise SystemExit(main())
