#!/usr/bin/env python3
"""檔案用途：提供 workflow-core projection/bootstrap 的最小可執行骨架。"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from workflow_core_manifest import (  # noqa: E402
    get_projection_artifact_path,
    get_required_live_paths,
    load_manifest,
    manifest_default_path,
    normalize_path,
    pattern_anchor,
)


EXIT_PASS = 0
EXIT_WARN = 10
EXIT_FAIL = 20
EXIT_ERROR = 30
INDEX_PATH = "doc/implementation_plan_index.md"
INDEX_PLACEHOLDER = "# Implementation Plan Index\n\n> Placeholder generated by workflow_core_projection.py bootstrap stub.\n"


def classify_required_live_paths(repo_root: Path, manifest: dict) -> dict[str, list[str]]:
    existing: list[str] = []
    missing: list[str] = []
    for pattern in get_required_live_paths(manifest):
        anchor = pattern_anchor(pattern)
        if not anchor:
            missing.append(pattern)
            continue
        target = repo_root / anchor
        if target.exists():
            existing.append(pattern)
        else:
            missing.append(pattern)
    return {"existing": existing, "missing": missing}


def bootstrap_overlay_index(repo_root: Path) -> str | None:
    index_path = repo_root / INDEX_PATH
    if index_path.exists():
        return None
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(INDEX_PLACEHOLDER, encoding="utf-8")
    return normalize_path(str(index_path.relative_to(repo_root)))


def run_projection_stub(repo_root: Path, manifest_path: Path, bootstrap_overlay_index_file: bool = False) -> dict:
    manifest = load_manifest(manifest_path)
    projection_artifact_path = get_projection_artifact_path(manifest)
    checks = classify_required_live_paths(repo_root, manifest)

    created_paths: list[str] = []
    missing_paths = list(checks["missing"])
    notes: list[str] = []

    if bootstrap_overlay_index_file and INDEX_PATH in missing_paths:
        created = bootstrap_overlay_index(repo_root)
        if created:
            created_paths.append(created)
            missing_paths = [item for item in missing_paths if item != INDEX_PATH]
            notes.append("bootstrapped downstream overlay index placeholder")

    if missing_paths:
        status = "fail"
        notes.append("projection/bootstrap stub found missing required live paths")
    elif created_paths:
        status = "warn"
        notes.append("projection/bootstrap stub created placeholder downstream overlay artifacts")
    else:
        status = "pass"
        notes.append("projection/bootstrap stub validated required live path anchors")

    return {
        "status": status,
        "repo_root": str(repo_root.resolve()),
        "manifest_path": str(manifest_path.resolve()),
        "projection_artifact_path": projection_artifact_path,
        "existing_required_live_paths": checks["existing"],
        "missing_required_live_paths": missing_paths,
        "created_paths": created_paths,
        "notes": notes,
    }


def format_text_report(result: dict) -> str:
    lines = [
        f"workflow-core projection stub: {result['status']}",
        f"repo_root: {result['repo_root']}",
        f"manifest_path: {result['manifest_path']}",
        f"projection_artifact_path: {result['projection_artifact_path']}",
    ]
    lines.append(f"existing_required_live_paths: {len(result['existing_required_live_paths'])}")
    for item in result["existing_required_live_paths"]:
        lines.append(f"  - {item}")
    lines.append(f"missing_required_live_paths: {len(result['missing_required_live_paths'])}")
    for item in result["missing_required_live_paths"]:
        lines.append(f"  - {item}")
    if result["created_paths"]:
        lines.append("created_paths:")
        for item in result["created_paths"]:
            lines.append(f"  - {item}")
    if result["notes"]:
        lines.append("notes:")
        for item in result["notes"]:
            lines.append(f"  - {item}")
    return "\n".join(lines)


def exit_code_for_status(status: str) -> int:
    if status == "pass":
        return EXIT_PASS
    if status == "warn":
        return EXIT_WARN
    if status == "fail":
        return EXIT_FAIL
    return EXIT_ERROR


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd(), help="Repo 根目錄（預設：目前目錄）")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="workflow-core canonical manifest path（預設：<repo-root>/core_ownership_manifest.yml）",
    )
    parser.add_argument(
        "--bootstrap-overlay-index",
        action="store_true",
        help="若 doc/implementation_plan_index.md 缺失，建立最小 placeholder 作為 bootstrap stub",
    )
    parser.add_argument("--json", action="store_true", help="輸出 JSON")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    manifest_path = args.manifest.resolve() if args.manifest else manifest_default_path(repo_root)
    try:
        result = run_projection_stub(
            repo_root=repo_root,
            manifest_path=manifest_path,
            bootstrap_overlay_index_file=bool(args.bootstrap_overlay_index),
        )
    except Exception as exc:
        if args.json:
            print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False, indent=2), file=sys.stderr)
        else:
            print(f"workflow-core projection stub error: {exc}", file=sys.stderr)
        return EXIT_ERROR

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(format_text_report(result))
    return exit_code_for_status(result["status"])


if __name__ == "__main__":
    raise SystemExit(main())
