#!/usr/bin/env python3
"""檔案用途：為 downstream repo 產生 restricted Obsidian mount contract sample。"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


EXIT_PASS = 0
EXIT_FAIL = 20
EXIT_ERROR = 30

DEFAULT_OUTPUT_DIR = ".devcontainer"
SNIPPET_FILENAME = "devcontainer.obsidian-restricted.jsonc"
GUIDE_FILENAME = "OBSIDIAN_RESTRICTED_MOUNT.md"
GITIGNORE_ENTRY = "obsidian-knowledge/"
HOST_ENV_VAR = "OBSIDIAN_HOST_VAULT_ROOT"
ACCESS_ROOT = "/workspaces/${localWorkspaceFolderBasename}/obsidian-knowledge"
PENDING_REVIEW_REL = "10-inbox/pending-review-notes"


def render_devcontainer_snippet() -> str:
    payload = {
        "remoteEnv": {
            "OBSIDIAN_VAULT_ROOT": ACCESS_ROOT,
            "OBSIDIAN_INDEX_ROOT": f"{ACCESS_ROOT}/00-indexes",
            "OBSIDIAN_REVIEWED_ROOT": f"{ACCESS_ROOT}/20-reviewed",
            "OBSIDIAN_PENDING_REVIEW_ROOT": f"{ACCESS_ROOT}/{PENDING_REVIEW_REL}",
            "OBSIDIAN_CONSUMER_PROFILE": "restricted",
        },
        "mounts": [
            f"source=${{localEnv:{HOST_ENV_VAR}}}/00-indexes,target={ACCESS_ROOT}/00-indexes,type=bind",
            f"source=${{localEnv:{HOST_ENV_VAR}}}/20-reviewed,target={ACCESS_ROOT}/20-reviewed,type=bind",
            f"source=${{localEnv:{HOST_ENV_VAR}}}/{PENDING_REVIEW_REL},target={ACCESS_ROOT}/{PENDING_REVIEW_REL},type=bind",
        ],
    }
    return (
        "// Generated by workflow_core_obsidian_restricted_mount.py\n"
        "// Merge this snippet into the downstream repo's active .devcontainer/devcontainer.json or local override.\n"
        "// This contract keeps Obsidian access single-root and restricted to indexes + reviewed content.\n"
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + "\n"
    )


def render_mount_guide() -> str:
    return """# Downstream Restricted Obsidian Mount

這份 sample 只適用於 downstream / 新專案工作區的 restricted consumer profile。

## 目的

- 讓 downstream workflow 在需要時可讀取 Obsidian 的 `00-indexes/` 與最小必要 `20-reviewed/`
- 讓 downstream workflow 以 `10-inbox/pending-review-notes/` 作為 default writable mount，並僅在 capture / triage 命中時對這個區域做 on-demand read
- 保持 single-root workspace；Explorer 看到的 access surface 會落在 repo 內的 `obsidian-knowledge/`
- 避免把 full vault、`10-inbox/reviewed-sync-candidates/`、`30-archives/` 帶進 downstream 預設工作面

## 使用方式

1. 在宿主機設定環境變數 `OBSIDIAN_HOST_VAULT_ROOT`，值為實際 Obsidian vault 根目錄。
2. 把 `devcontainer.obsidian-restricted.jsonc` 內的 `remoteEnv` 與 `mounts` 片段合併到目前使用中的 `.devcontainer/devcontainer.json` 或本機 override。
3. 重新 `Reopen in Container`。

## 預期 access surface

- `obsidian-knowledge/00-indexes/`
- `obsidian-knowledge/20-reviewed/`
- `obsidian-knowledge/10-inbox/pending-review-notes/`

其中 `10-inbox/pending-review-notes/` 是 downstream default 的 writable inbox zone，但不屬於啟動前置閱讀面，只在 capture / triage 命中時 on-demand read。

這不是 multi-root workspace；VS Code 仍只打開 downstream repo 這一個 root。

## 明確禁止的預設 mount

- `10-inbox/reviewed-sync-candidates/`
- `30-archives/`
- 任何 full-vault mount

對 downstream restricted consumer profile 而言，`10-inbox/reviewed-sync-candidates/` 不應提供 read 或 write。

## Git 建議

`obsidian-knowledge/` 應保持在 `.gitignore` 中，避免外部 mount surface 汙染 repo status。
"""


def write_text_file(target_path: Path, content: str, *, force: bool) -> str:
    if target_path.exists():
        existing = target_path.read_text(encoding="utf-8")
        if existing == content:
            return "unchanged"
        if not force:
            raise RuntimeError(f"refusing to overwrite existing file without --force: {target_path}")
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(content, encoding="utf-8")
    return "updated" if target_path.exists() else "created"


def ensure_gitignore_entry(repo_root: Path) -> bool:
    gitignore_path = repo_root / ".gitignore"
    if gitignore_path.exists():
        content = gitignore_path.read_text(encoding="utf-8")
    else:
        content = ""

    if GITIGNORE_ENTRY in {line.strip() for line in content.splitlines()}:
        return False

    block = (
        "\n# Downstream restricted Obsidian access surface\n"
        f"{GITIGNORE_ENTRY}\n"
    )
    gitignore_path.write_text(content.rstrip("\n") + block, encoding="utf-8")
    return True


def run_generate_downstream_obsidian_mount(
    repo_root: Path,
    output_dir: Path | None = None,
    *,
    force: bool = False,
    update_gitignore: bool = True,
) -> dict:
    resolved_repo_root = repo_root.resolve()
    resolved_output_dir = (output_dir or (resolved_repo_root / DEFAULT_OUTPUT_DIR)).resolve()

    snippet_path = resolved_output_dir / SNIPPET_FILENAME
    guide_path = resolved_output_dir / GUIDE_FILENAME

    snippet_status = write_text_file(snippet_path, render_devcontainer_snippet(), force=force)
    guide_status = write_text_file(guide_path, render_mount_guide(), force=force)
    gitignore_updated = ensure_gitignore_entry(resolved_repo_root) if update_gitignore else False

    return {
        "status": "pass",
        "repo_root": str(resolved_repo_root),
        "output_dir": str(resolved_output_dir),
        "snippet_path": str(snippet_path),
        "snippet_status": snippet_status,
        "guide_path": str(guide_path),
        "guide_status": guide_status,
        "gitignore_updated": gitignore_updated,
        "notes": [
            "generated downstream restricted Obsidian mount sample",
            "downstream default remains single-root and restricted-consumer only",
        ],
    }


def format_text_report(result: dict) -> str:
    lines = [
        f"workflow-core downstream obsidian mount: {result['status']}",
        f"repo_root: {result['repo_root']}",
        f"output_dir: {result['output_dir']}",
        f"snippet_path: {result['snippet_path']} ({result['snippet_status']})",
        f"guide_path: {result['guide_path']} ({result['guide_status']})",
        f"gitignore_updated: {result['gitignore_updated']}",
    ]
    if result.get("notes"):
        lines.append("notes:")
        for note in result["notes"]:
            lines.append(f"  - {note}")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd(), help="downstream repo 根目錄")
    parser.add_argument("--output-dir", type=Path, default=None, help="sample 輸出目錄（預設：<repo-root>/.devcontainer）")
    parser.add_argument("--force", action="store_true", help="允許覆蓋既有 sample 檔案")
    parser.add_argument("--skip-gitignore", action="store_true", help="不要更新 repo .gitignore")
    parser.add_argument("--json", action="store_true", help="輸出 JSON")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    output_dir = args.output_dir.resolve() if args.output_dir else None
    try:
        result = run_generate_downstream_obsidian_mount(
            repo_root=repo_root,
            output_dir=output_dir,
            force=bool(args.force),
            update_gitignore=not args.skip_gitignore,
        )
    except Exception as exc:
        if args.json:
            print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False, indent=2), file=sys.stderr)
        else:
            print(f"workflow-core downstream obsidian mount error: {exc}", file=sys.stderr)
        return EXIT_ERROR

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(format_text_report(result))
    return EXIT_PASS if result["status"] == "pass" else EXIT_FAIL


if __name__ == "__main__":
    raise SystemExit(main())
